- name: springald_metal_dir_create
  become: true
  become_method: sudo
  file:
    path: "{{ item }}"
    state: directory
    mode: '0755'
    recurse: yes
  loop:
    - /metal
    - /metal/ansible_lock_dir
    - /metal/scripts
    - /metal/src
    - /dev/shm/metal_lock/