---
- include_tasks: client_metal_dir_create.yaml
- include_tasks: client_configure_vlan_interface.yaml
- include_tasks: client_install_packages.yaml
- include_tasks: client_configure_os_limits.yaml
- include_tasks: client_firewall.yaml
- include_tasks: client_fail2ban.yaml